"""Password hashing and signed access-token utilities."""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import secrets
import time

import jwt

from src.config import JWT_SECRET


def hash_password(password: str) -> str:
    """Hash a password using PBKDF2-HMAC-SHA256 with a random salt."""
    if len(password) < 8:
        raise ValueError("Password must contain at least 8 characters")
    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, 310_000)
    return "pbkdf2_sha256$310000$" + base64.urlsafe_b64encode(salt).decode() + "$" + base64.urlsafe_b64encode(digest).decode()


def verify_password(password: str, encoded_hash: str) -> bool:
    """Verify a password against a hash generated by :func:`hash_password`."""
    try:
        algorithm, iterations, salt_value, digest_value = encoded_hash.split("$", 3)
        if algorithm != "pbkdf2_sha256":
            return False
        salt = base64.urlsafe_b64decode(salt_value.encode())
        expected = base64.urlsafe_b64decode(digest_value.encode())
        actual = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, int(iterations))
        return hmac.compare_digest(actual, expected)
    except (ValueError, TypeError):
        return False


def create_access_token(user_id: int, role: str, email: str) -> str:
    """Create a short-lived JWT for an authenticated user."""
    now = int(time.time())
    payload = {"sub": str(user_id), "role": role, "email": email, "iat": now, "exp": now + 8 * 60 * 60}
    return jwt.encode(payload, JWT_SECRET, algorithm="HS256")


def decode_access_token(token: str) -> dict:
    """Decode and validate an access token."""
    return jwt.decode(token, JWT_SECRET, algorithms=["HS256"])
